In [4]:
import datetime

In [5]:
datetime.datetime.now()

datetime.datetime(2019, 12, 7, 20, 28, 49, 176762)

In [6]:
import numpy as np

In [10]:
y = np.array([44,21,37])
print (y)
print (y.shape)
x = np.array([[12,13],[14,15]])
x

[44 21 37]
(3,)


array([[12, 13],
       [14, 15]])

In [11]:
X = np.array([[4, 5],[2, 4],[3, 3]])
b = np.array([3,-2])
print(np.dot(X, b))

[ 2 -2  3]
